# Generated by Django 5.0.7 on 2024-07-12 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0002_alter_category_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
