# Generated by Django 5.0.7 on 2024-07-13 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0004_alter_productvariant_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='color',
            field=models.CharField(choices=[('black', 'Black'), ('white', 'White'), ('gray', 'Gray'), ('red', 'Red'), ('blue', 'Blue'), ('green', 'Green')], max_length=50, verbose_name='Color'),
        ),
    ]
