# Generated by Django 5.0.7 on 2024-08-04 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0008_alter_product_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productvariant',
            old_name='product',
            new_name='product_id',
        ),
        migrations.AlterUniqueTogether(
            name='productvariant',
            unique_together={('product_id', 'size', 'color')},
        ),
    ]
