# Generated by Django 5.0.7 on 2024-08-04 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0010_rename_product_id_productvariant_product_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductVariant',
        ),
    ]
